# -*- coding: utf-8 -*-
"""NetworkX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vwz5a7QJITrRCvogpELb5ODG424RwgEI
"""

from IPython.core.display import display, HTML
display(HTML("<style>.container {width:90% !important;}</style>"))

import networkx as nx

g1=nx.Graph() #그래프생성
g1.add_node(1)#노드생성
g1.add_node(2)
g1.add_node(3)
g1.add_node(4)
g1.add_edges_from([(1,2),(2,3)])#edge 생성
nx.draw(g1,with_labels=True)#그래프 그리기



